/* OP_SDME_EXT.C
*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 * opcodes for ScarletDME extension function
 * START-DESCRIPTION:
 *
 * Opcodes:
 *    op_sdme_ext    SDME.EXT   
 *    for basic function SDME.EXT(Function_id, IsArgMV, Arg)
 *    where:
 *    Function_Id = the integer value used to identify what c code / function is execute.
 *    IsArgMV     = If passing a multiple arguments in Arg, set to true, otherwise false.  
 *    Arg         = string value passed to the c code / function. For functions requiring multiple arguments, set IsArgMV to true 
 *                  and pass arguments in a FIELD_MARK separated string, with a maximum of ?10? fields??
 *
 * END-DESCRIPTION
 *
 
 * START-CODE
 */

#include "sd.h"
#include <linux/limits.h>

#include "SDME_EXT.h"

extern void sdme_py(int key, char* Arg);
extern void sdme_crypt(int key, char* Arg0, char* Arg1); 

char *    SDMEArgArray[SDMEE_Max_Args];          /* create an array of pointers, for string arguments (for SDME.EXT call ) not sure if this is correct */

int   Dcount(char* src, char* delim_str);                   /* Dcount from qmclilib */
char* Extract(char* src, int fno, int vno, int svno);       /* Extract from qmclilib */
char* NullString(void); 


/* ======================================================================
   op_sdme_ext()   op code for BASIC function  SDME.EXT   
   rtnval = SDME.EXT(Arg,IsArgMV,key)
   rem: code generated by BCOMP will be
   LDSLCL   RTNVAL    Load onto stack short local variable address for RTNVAL
   LDSLCL   ARG       Load onto stack short local variable address for ARG
   LDSLCL   ISARGMV   Load onto stack short local variable address for ISARGMV
   LDSINT   key       Load onto stack short integer
   SDME_EXT           (op code for op_sdme_ext here)
   STOR               Store onto stack return value in rtnval

      Stack:
        +=============================++=============================+
        +       STACK On Entry        ++       STACK On Exit         +
        +=============================++=============================+
estack> +    next available descr     ++    next available descr     +
        +=============================++=============================+
        +  descriptor w/ integer      ++  Addr to descr for RTNVAL   +
        +      key value              ++                             +
        +=============================++=============================+
        +  descriptor w/ integer      ++   
        +      IsArgMV                ++
        +=============================++
        + Addr to descriptor for Arg  ++   
        +=============================++
		
	   patterned from op_ospath() in op_dio2.c */

void op_sdme_ext() {


  char myErrMsg[SDMEE_ErrMsg_LEN + 1];    /* hardcoded max string length is set to 512 char need to do something more "durable" */
  int32_t myval_len;
  int32_t mybuf_sz;
  char* myval_buffer;                      /* buffer for past value string  */
  STRING_CHUNK* str;
  int argIdx;
  int argCnt;
  int16_t key;
  int16_t IsArgMV;

  char* myFM = "\xFE";

  DESCRIPTOR* descr;
  
  /* set the process.status flag to  "successful"      */
  /* User can retrieve this status with the BASIC function STATUS()*/
    process.status = 0;

  /* Get action key */
  descr = e_stack - 1;   /* e_stack - 1 points to key descriptor */
  GetInt(descr);
  key = (int16_t)(descr->data.value);
  k_pop(1);   /* after pop() e_stack - 1 points to descr which holds ISArgMV  */

  /* Get IsArgMV Flag */
  descr = e_stack - 1;
  GetInt(descr);
  IsArgMV = (int16_t)(descr->data.value);
  k_pop(1);   /* * after pop() e_stack - 1 points to descr which holds ARG */

  /* Get val string */
  descr = e_stack - 1;
  k_get_string(descr);
  str = descr->data.str.saddr;
  /* is there something there? */
  if (str == NULL){
	  myval_len = 0;  
    mybuf_sz = 1;              /* room for string terminator */
  }else{
	 myval_len =  str->string_len;
     mybuf_sz  =  myval_len+1; /* room for string terminator */
  }
  
  /* allocate space for val string */
  myval_buffer = malloc(mybuf_sz * sizeof(char));
  if (myval_buffer == NULL){
  /* so here is a question, what to do if we cannot allocate memory?
     Looking thru the code SD sometimes checks and other times does not.
	 For now we are at least going to say something about it, and jump out  */
	 snprintf( myErrMsg, SDMEE_ErrMsg_LEN,"Unable to allocate buffer for argument in op_sdme_ext\n");
	 printf("%s\n",myErrMsg);
	 return;
  }

  /* move the passed argument string to our buffer */
  if (myval_len == 0){
	  myval_buffer[0] = '\0';
  } else {
   /* rem string length returned by k_get_c_string excludes terminator in count!*/ 
      myval_len = k_get_c_string(descr, myval_buffer, myval_len);
  }
  
  k_dismiss();   /* done with passed arg  descriptor */
                 /* Things to note                   */  
                 /* we use dismiss() instead of pop() because this is a string */ 
                 /* which may be made up of a linked list of string blocks     */
                 /* Using pop would not free the sting blocks                  */
                 /* After dismiss() e_stack  points to descr which will receive RTNVAL */

/* now extract arguments from the past arg string */

  if (myval_len == 0) {
	  argCnt = 1;                       /* always one args */
	  SDMEArgArray[0] = NullString();   /* simply a null string */

  }else{ 

    if (IsArgMV != 0){             /* MV Arg set */
  /*  Get number of fields in ARG */
      argCnt = Dcount(myval_buffer, myFM);
	/* if we found more args than we can process, only extract what we can hold */
	    if (argCnt > SDMEE_Max_Args) {
		    argCnt = SDMEE_Max_Args;
      }
	
	    for (argIdx = 0; argIdx < argCnt; argIdx++) { 
        /* rem Extract allocates our buffer space */
	      SDMEArgArray[argIdx]	= Extract(myval_buffer, argIdx+1, 0, 0);
	    }
    } else {  /* MV Flag not set, */
        argCnt = 1;                       /* always one args */
        SDMEArgArray[0] = myval_buffer;   /* we just point to the value buffer created earlier */  
    }
  }	  
  
  switch (key) {
	  
	  case  SDMEE_TestIt: 
	/* simple test to see if any of this works, output args to stdout  */
	    for (argIdx = 0; argIdx < argCnt; argIdx++) {
	      printf("Arg %d of %d\r\n",argIdx+1, argCnt);
 	      printf("'%s'\r\n",SDMEArgArray[argIdx]);
	    }
      snprintf( myErrMsg, SDMEE_ErrMsg_LEN, "op_sdme_ext() found %d args\n", argCnt);
      k_put_c_string(myErrMsg, e_stack);   /* sets as descr as type string and place the value in myErrMsg into it */
                                           /* this will then get transferred to RTNVAL via */
      e_stack++;	
      break; 


    case SDMEE_EncryptHX:
    case SDMEE_DecryptHX:
    /* encryption  and decrytion */
      sdme_crypt(key,SDMEArgArray[0],SDMEArgArray[1]);  
      break;
  
    case SDMEE_PyInit:  
    case SDMEE_PyFinal:   
    case SDMEE_PyRunStr:  
    case SDMEE_PyRunFile: 
    case SDMEE_PyGetAtt :
  /* embedding Python functions*/
      sdme_py(key, SDMEArgArray[0]);
      break;


    default:
      /* unknown key */
      process.status = 1;    /* BASIC STATUS() function return value */
      snprintf( myErrMsg, SDMEE_ErrMsg_LEN, "op_sdme_ext() Invalid Key: %d\n", key);
      k_put_c_string(myErrMsg, e_stack);   /* sets as descr as type string and place the value in myErrMsg into it */
                                           /* this will then get transferred to RTNVAL via */
      e_stack++;

  }
  
  /* release our arg Buffers  */
  for (argIdx = 0; argIdx < SDMEE_Max_Args; argIdx++) {
	  if (SDMEArgArray[argIdx] != NULL ){
	    free(SDMEArgArray[argIdx]);
	    SDMEArgArray[argIdx] = NULL;
	  }
  }  
  /* and the val buffer */	
  if (myval_buffer != NULL){
    if (IsArgMV != 0) {      /* rem if IsArgMV not set, we pointed DMEArgArray[0] to myval_buffer*/
	    free(myval_buffer);    /* do not want to attempt to free the memory again!!*/
    } 
  }
  
  return;
}

/* ======================================================================
   Dcount()  -  Count fields, values or subvalues                       
   copied from qmclilib.c                                              */

int Dcount(char* src, char* delim_str) {
  int32_t src_len;
  char* p;
  int32_t ct = 0;
  char delim;

  if (strlen(delim_str) != 0) {
    delim = *delim_str;

    src_len = strlen(src);
    if (src_len != 0) {
      ct = 1;
      while ((p = memchr(src, delim, src_len)) != NULL) {
        src_len -= (1 + p - src);
        src = p + 1;
        ct++;
      }
    }
  }

  return ct;
}

/* ======================================================================
   Extract()  -  Extract field, value or subvalue                      
   copied from qmclilib.c                                              */

char* Extract(char* src, int fno, int vno, int svno) {
  int32_t src_len;
  char* p;
  char* result;

  src_len = strlen(src);
  if (src_len == 0)
    goto null_result; /* Extracting from null string */

  /* Setp 1  -  Initialise variables */

  if (fno < 1)
    fno = 1;

  /* Step 2  -  Position to start of item */

  /* Skip to start field */

  while (--fno) {
    p = memchr(src, FIELD_MARK, src_len);
    if (p == NULL)
      goto null_result; /* No such field */
    src_len -= (1 + p - src);
    src = p + 1;
  }
  p = memchr(src, FIELD_MARK, src_len);
  if (p != NULL)
    src_len = p - src; /* Adjust to ignore later fields */

  if (vno < 1)
    goto done; /* Extracting whole field */

  /* Skip to start value */

  while (--vno) {
    p = memchr(src, VALUE_MARK, src_len);
    if (p == NULL)
      goto null_result; /* No such value */
    src_len -= (1 + p - src);
    src = p + 1;
  }

  p = memchr(src, VALUE_MARK, src_len);
  if (p != NULL)
    src_len = p - src; /* Adjust to ignore later values */

  if (svno < 1)
    goto done; /* Extracting whole value */

  /* Skip to start subvalue */

  while (--svno) {
    p = memchr(src, SUBVALUE_MARK, src_len);
    if (p == NULL)
      goto null_result; /* No such subvalue */
    src_len -= (1 + p - src);
    src = p + 1;
  }
  p = memchr(src, SUBVALUE_MARK, src_len);
  if (p != NULL)
    src_len = p - src; /* Adjust to ignore later fields */

done:
  result = malloc(src_len + 1);
  memcpy(result, src, src_len);
  result[src_len] = '\0';
  return result;

null_result:
  return NullString();
}


char* NullString() {
  char* p;

  p = malloc(1);
  *p = '\0';
  return p;
}